# Generated by Django 2.2.12 on 2024-03-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20240315_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
