# Generated by Django 2.2.12 on 2024-03-16 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address'),
        ),
    ]
