# Generated by Django 2.2.12 on 2024-03-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20240316_0545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
