# Generated by Django 5.0.2 on 2024-02-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='product_img', verbose_name='Main Image')),
                ('image2', models.ImageField(upload_to='product_img', verbose_name='Inside1 Image')),
                ('image3', models.ImageField(upload_to='product_img', verbose_name='Inside2 Image')),
                ('type', models.CharField(max_length=255, verbose_name='Cloth Type')),
                ('fabric', models.CharField(max_length=255, verbose_name='Fabric')),
                ('pattern', models.CharField(max_length=255, verbose_name='Pattern')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
