# Generated by Django 5.0.2 on 2024-03-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_user_alter_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
